/* ==================================================================
 * AppEvent.java - 29/05/2020 3:35:12 pm
 * 
 * Copyright 2020 SolarNetwork.net Dev Team
 * 
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation; either version 2 of 
 * the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 
 * 02111-1307 USA
 * ==================================================================
 */

package net.solarnetwork.central.domain;

import java.time.Instant;
import java.util.Map;

/**
 * An application event.
 * 
 * <p>
 * Application events are generated by SolarNetwork applications themselves.
 * </p>
 * 
 * @author matt
 * @version 1.0
 * @since 2.5
 */
public interface AppEvent {

	/**
	 * Get the event topic.
	 * 
	 * <p>
	 * By convention topics are path-like structures like
	 * {@literal datum/agg/calculated}.
	 * </p>
	 * 
	 * @return the event topic, never {@literal null}
	 */
	String getTopic();

	/**
	 * Get the date the event was created.
	 * 
	 * @return the creation date, never {@literal null}
	 */
	Instant getCreated();

	/**
	 * Get the properties of the event.
	 * 
	 * <p>
	 * The available properties is topic-specific.
	 * </p>
	 * 
	 * @return the event properties, never {@literal null}
	 */
	Map<String, ?> getEventProperties();

}
