CREATE SCHEMA IF NOT EXISTS solaroscp;

ALTER DEFAULT PRIVILEGES IN SCHEMA solaroscp REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaroscp REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaroscp REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solaroscp REVOKE ALL ON TYPES FROM PUBLIC;
