CREATE SCHEMA IF NOT EXISTS solardnp3;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardnp3 REVOKE ALL ON FUNCTIONS FROM PUBLIC;
