CREATE SCHEMA IF NOT EXISTS solardatm;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardatm REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardatm REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardatm REVOKE ALL ON FUNCTIONS FROM PUBLIC;
