CREATE SCHEMA IF NOT EXISTS solarbill;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill REVOKE ALL ON TYPES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT SELECT ON TABLES TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON SEQUENCES TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON FUNCTIONS TO solaruser;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON TYPES TO solaruser;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON TABLES TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON SEQUENCES TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON FUNCTIONS TO solarjobs;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarbill GRANT ALL ON TYPES TO solarjobs;
