CREATE SCHEMA IF NOT EXISTS solarcommon;

ALTER DEFAULT PRIVILEGES IN SCHEMA solarcommon REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarcommon REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solarcommon REVOKE ALL ON FUNCTIONS FROM PUBLIC;
