CREATE SCHEMA IF NOT EXISTS solardin;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON FUNCTIONS FROM PUBLIC;
