/* ==================================================================
 * DatumAppEventProducer.java - 15/06/2020 5:31:59 pm
 * 
 * Copyright 2020 SolarNetwork.net Dev Team
 * 
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation; either version 2 of 
 * the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 
 * 02111-1307 USA
 * ==================================================================
 */

package net.solarnetwork.central.datum.biz;

import java.util.Set;
import net.solarnetwork.central.datum.domain.DatumAppEvent;
import net.solarnetwork.domain.Identity;
import net.solarnetwork.service.LocalizedServiceInfoProvider;
import net.solarnetwork.settings.SettingSpecifierProvider;

/**
 * API for a service that produces {@link DatumAppEvent} instances.
 * 
 * <p>
 * This API is designed to support dynamic UIs via the
 * {@link SettingSpecifierProvider} API, by providing the set of supported event
 * topics at runtime.
 * </p>
 * 
 * @author matt
 * @version 2.0
 */
public interface DatumAppEventProducer
		extends Identity<String>, SettingSpecifierProvider, LocalizedServiceInfoProvider {

	/**
	 * Get the set of event topics generated by this service.
	 * 
	 * @return the event topics, never {@literal null}
	 */
	Set<String> getProducedDatumAppEventTopics();

}
