error.dataRequest = Error requesting data: {0}

error.datumStream.noProperties = No stream properties are configured.
error.datumStream.notFullyConfigured = The datum stream is not fully configured.

error.missingTimestamp = No timestamp was provided with the data.

validationType.energy-spike.key = Energy Spike
validationType.energy-spike.desc = Identify abnormally large energy readings based on device characteristics, \
	and reduce the reported value appropriately.

sourceIdMap.key = Source ID Mapping
sourceIdMap.desc = A map or comma-delimited mapping list of component IDs to associated source ID values. \
	For example as JSON <code>{"12345":"INV/1","23456":"INV/2"}</code> or as a string \
	<code>12345=INV/1,23456=INV/2</code>.

upperCaseSourceId.key = Upper Case Source ID
upperCaseSourceId.desc = When enabled, make generated source ID components all upper case. Does not \
	affect explicitly mapped source ID values.

virtualSourceIds.key = Virtual Source IDs
virtualSourceIds.desc = A list or comma-delimited list of virtual IDs to generate with expressions. \
	For example as JSON <code>["GEN/1","GEN/2"]</code> or as a string <code>GEN/1,GEN/2</code>.

multiStreamMaximumLag.key = Multiple Stream Lag Tolerance
multiStreamMaximumLag.desc = The maximum amount of time to accommodate partially reported \
	data before giving up. When polling for multiple datum streams and any stream lags behind other \
	streams, the polling reference time will not advance for at most this duration. Can be specified \
	as an ISO duration like <code>PT2H</code> for "2 hours" or an integer number of seconds.

operationalDateRanges.key = Operational Date Ranges
operationalDateRanges.desc = A map or comma-delimited mapping list of device component references to \
	an date interval representing the time period the device should be considered as operational. \
	The date interval syntax is <code>START_DATE/END_DATE</code> where each date is optional and \
	formatted as an ISO 8601 timestamp. For example <code>/abc/123=2020-01-01T05:00:00Z/</code> means device \
	<code>/abc/123</code> became operational on 1 Jan 2020; <code>/abc/123=/2022-01-01T05:00:00Z</code> means \
	the device stopped being operational on 1 Jan 2022; \
	<code>/abc/123=2020-01-01T05:00:00Z/2022-01-01T05:00:00Z</code> means the device was operational between \
	1 Jan 2020 and 1 Jan 2022.

validationIgnore.key = Validation Ignore
validationIgnore.desc = A list or comma-delimited list of validation types to ignore. Validation types \
	are implementation-specific keywords, for example <code>energy-spike</code>.

energyValidationThreshold.key = Energy Validation Threshold
energyValidationThreshold.desc = A multiplication factor to apply to the expected maximum energy \
	value for a given time period, such that an energy value that exceeds it should be considered invalid.
