title = Fronius Datum Stream

apiKey.key = API Key
apiKey.desc = The user API key.

apiSecret.key = API Secret
apiSecret.desc = The user API secret.

error.apiKey.missing = API key is required.
error.apiSecret.missing = API secret is required.
