app:
  meta:
    name: SolarOCPP
    key: ocpp
  cache.persistence.path: "var/cache"
  datasource:
    hikari:
      minimumIdle: 1
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      readOnly: false
    url: "jdbc:postgresql://localhost/solarnetwork_unittest"
    username: "solartest"
    password: "solartest"
    initialize: false
  datum:
    stream-metadata-cache:
      ttl: 300
      heap-max-entries: 10000
      disk-max-size-mb: 5
    stream-metadata-id-cache:
      ttl: 900
      heap-max-entries: 10000
      disk-max-size-mb: 5
  mqtt.client:
    io-thread-count: 2
    wire-logging-enabled: false
  node-ownership-cache:
    ttl: 60
    heap-max-entries: 10000
    disk-max-size-mb: 5
  ocpp.async-action-status-updater:
    connection-recovery-delay: 5000
    stat-log-update-count: 1000
    update-delay: 0
    buffer-removal-lag-alert-threshold: 1000
  ocpp.async-status-updater:
    flush-delay: "3s"
  ocpp.auth-service:
    wildcard-id-tag-prefixes:
      - "vid:"
  ocpp.v16:
    cs:
      boot-notification:
        heartbeat-interval-seconds: 300
    mqtt.instr-handler:
      mqtt-topic: "instr/OCPP_v16"
      subscribe-timeout: 30
      publish-only: false
    ws:
      partial-message-maximum-size: 1048576
      partial-message-maximum-size-exceeded-close: true
      pending-message-timeout: 120000
      ping-frequency-secs: 50
      shutdown-task-post-delay: "5s"
      shutdown-task-max-wait: "1m"
  ocpp.v201:
    ws:
      partial-message-maximum-size: 1048576
      pending-message-timeout: 120000
      ping-frequency-secs: 50
      shutdown-task-post-delay: "5s"
      shutdown-task-max-wait: "1m"
  solarflux:
    connection:
      uid: "SolarFlux-${app.meta.instance-id}"
      mqtt-stats.log-frequency: 1000
      mqtt-config:
        server-uri: "mqtt://solarflux.solarnetwork:1883"
        client-id: "solarocpp-${app.meta.instance-id}"
        username: "USERNAME_HERE"
        password: "PASSWORD_HERE"
        connect-timeout-seconds: 10
        keep-alive-seconds: 60
        read-timeout-seconds: 0
        write-timeout-seconds: -1
    datum-publish:
      publish-qos-level: 0
    user-events:
      publish-qos-level: 0
  solarqueue:
    connection:
      uid: "SolarOCPP-${app.meta.instance-id}"
      mqtt-stats.log-frequency: 200
      mqtt-config:
        server-uri: "mqtt://localhost:1883"
        client-id: "solarocpp-${app.meta.instance-id}"
        username: "USERNAME_HERE"
        password: "PASSWORD_HERE"
        clean-session: true
        connect-timeout-seconds: 10
        keep-alive-seconds: 60
        read-timeout-seconds: -1
        write-timeout-seconds: -1
  task.executor:
    thread-name-prefix: "SolarNet-"
    core-pool-size: 10
    max-pool-size: 10
    allow-core-thread-time-out: false
    accept-tasks-after-context-close: true
  task.scheduler:
    thread-name-prefix: "SolarNet-Sched-"
    pool-size: 2
    remove-on-cancel-policy: true
    accept-tasks-after-context-close: true
  user.events:
    async-appender:
      threads: 1
      stat-frequency: 1000
      queue-lag-alert-threshold: 1000

logging:
  level:
    ROOT: "INFO"
    org.mybatis.spring.mapper.ClassPathMapperScanner: "OFF"
    org.springframework.aop.framework.CglibAopProxy: "ERROR"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

management:
  endpoint:
    health:
      cache.time-to-live: "59s"
      show-details: "when_authorized"
      roles: "ROLE_OPS"
  endpoints:
    web:
      base-path: "/ops"
      exposure:
        include: "*"
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  configuration-properties:
    node-cache-flush: 900000
    ocpp-auth-cache-flush: 900000
    ocpp-charge-point-cache-flush: 900000
    ocpp-system-user-cache-flush: 900000
    user-cache-flush: 900000
    user-auth-token-cache-flush: 900000
    user-node-cache-flush: 900000
  mapper-locations: "classpath*:net/solarnetwork/**/mybatis/map/*.xml"
  type-aliases-package: >-
     net.solarnetwork.central.domain
     net.solarnetwork.central.datum.export.domain
     net.solarnetwork.central.instructor.domain
     net.solarnetwork.central.user.domain

server:
  compression:
    enabled: true
    mime-types: "application/json,application/javascript,image/svg+xml,text/css,text/html,text/plain,text/xml"
    min-response-size: 2048
  error.whitelabel.enabled: false
  port: 9085
  tomcat.threads:
    min-spare: 10
    max: 50

spring:
  jmx.enabled: false
  mvc.format:
    date: "iso"
    date-time: "iso"
    time: "iso"

---
spring:
  config.activate.on-profile: "development"
  thymeleaf.cache: false

app:
  datasource:
    url: "jdbc:postgresql://localhost/solarnetwork"
    username: "solarnet"
    password: "solarnet"

debug: true

server:
  forward-headers-strategy: "NATIVE"
  tomcat.redirect-context-root: true

---
spring:
  config.activate.on-profile: "production"

server:
  forward-headers-strategy: "NATIVE"
  tomcat.redirect-context-root: true
