//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.29 at 01:11:32 PM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openadr.org/DRAS/EventState", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.solarnetwork.central.dras.openadr1;
