app:
  meta:
    name: SolarIn
    key: in
  cache.persistence.path: "var/cache"
  datasource:
    hikari:
      minimumIdle: 1
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      readOnly: false
    url: "jdbc:postgresql://localhost/solarnetwork_unittest"
    username: "solartest"
    password: "solartest"
    initialize: false
  datum:
    stream-metadata-cache:
      ttl: 300
      heap-max-entries: 10000
      disk-max-size-mb: 100
    stream-metadata-id-cache:
      ttl: 900
      heap-max-entries: 10000
      disk-max-size-mb: 100
  email-throttle-cache:
    ttl: 600
    heap-max-entries: 1000
    disk-max-size-mb: 100
  mqtt.client:
    io-thread-count: 2
    wire-logging-enabled: false
  network-identity:
    network-identity-key: "replace:identity:here"
    terms-of-service: "classpath:/net/solarnetwork/central/in/config/placeholder-tos.txt"
    host: "localhost"
    port: 9083
    force-tls: false
    service-urls:
      node-dashboard: "http://localhost/node-dashboard"
      node-dataview: "http://localhost/node-dataview?nodeId={nodeId}"
      solardin: "http://localhost:9087"
      solarin-mqtt: "mqtt://localhost:1883"
      solarquery: "http://localhost:9082/solarquery"
      solaruser: "http://localhost:9081/solaruser"
  node.pki.cs:
    certificate-expire-days: 730
    signature-algorithm: "SHA256WithRSA"
  node-ownership-cache:
    ttl: 60
    heap-max-entries: 10000
    disk-max-size-mb: 100
  solarflux:
    connection:
      uid: "SolarFlux-@@SOLAR_FLUX_PUB_ID@@"
      mqtt-stats.log-frequency: 200
      mqtt-config:
        server-uri: "mqtt://solarflux.solarnetwork:1883"
        client-id: "solarin-${app.meta.instance-id}"
        username: "USERNAME_HERE"
        password: "PASSWORD_HERE"
        connect-timeout-seconds: 10
        keep-alive-seconds: 60
        read-timeout-seconds: 0
        write-timeout-seconds: -1
    datum-publish:
      publish-qos-level: 0
    user-events:
      publish-qos-level: 0
  solarin:
    async-collector:
      threads: 2
      shutdown-wait-secs: 30
      queue-size: 200
      queue-refill-threshold: 0.1
      queue-refill-wait-ms: 20
      stat-frequency: 200
      datum-cache-removal-alert-threshold: 500
    datum-buffer:
      temp-max-entries: 100
      heap-max-entries: 0
      disk-max-size-mb: 2000
    sqs-collector:
      region: "us-west-2"
      queue-name: "datum-queue"
      url: "https://sqs.us-west-2.amazonaws.com/1234567890/datum-queue"
      access-key: "ACCESS_KEY_HERE"
      secret-key: "SECRET_KEY_HERE"
      work-queue-size: 100
      work-item-max-wait: "5s"
      read-concurrency: 1
      write-concurrency: 2
      read-max-message-count: 10
      read-max-wait-time: "20s"
      read-sleep-min: "0s"
      read-sleep-max: "10s"
      read-sleep-throttle-step: "100ms"
      shutdown-wait: "30s"
      stat-frequency: 200
  solarqueue:
    connection:
      uid: "SolarIn-@@SOLAR_IN_ID@@"
      mqtt-stats.log-frequency: 200
      mqtt-config:
        server-uri: "mqtt://localhost:1883"
        client-id: "solarin-@@SOLAR_IN_ID@@"
        username: "USERNAME_HERE"
        password: "PASSWORD_HERE"
        clean-session: false
        connect-timeout-seconds: 10
        keep-alive-seconds: 60
        read-timeout-seconds: -1
        write-timeout-seconds: -1
    data-collector:
      node-datum-topic-template: "node/%s/datum"
      subscribe-qos-level: 1
  task.executor:
    thread-name-prefix: "SolarNet-"
    core-pool-size: 10
    max-pool-size: 10
    allow-core-thread-time-out: false
  task.scheduler:
    thread-name-prefix: "SolarNet-Sched-"
    pool-size: 2
    remove-on-cancel-policy: true
  user.reg:
    biz:
      network-certificate-subject-format: "UID=%s,O=SolarNetwork"
      approve-csr-maximum-wait-secs: 15
      node-certificate-renewal-period-months: 3
  user.events:
    async-appender:
      threads: 1
      stat-frequency: 500
      queue-lag-alert-threshold: 500

logging:
  level:
    ROOT: "INFO"
    org.mybatis.spring.mapper.ClassPathMapperScanner: "OFF"
    org.springframework.aop.framework.CglibAopProxy: "ERROR"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

management:
  endpoint:
    health:
      cache.time-to-live: "59s"
      show-details: "when_authorized"
      roles: "ROLE_OPS"
  endpoints:
    web:
      base-path: "/ops"
      exposure:
        include: "*"
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  configuration-properties:
    node-cache-flush: 900000
    user-cache-flush: 900000
    user-auth-token-cache-flush: 900000
    user-node-cache-flush: 900000
  mapper-locations: "classpath*:net/solarnetwork/**/mybatis/map/*.xml"
  type-aliases-package: >-
     net.solarnetwork.central.domain
     net.solarnetwork.central.datum.export.domain
     net.solarnetwork.central.instructor.domain
     net.solarnetwork.central.user.domain

server:
  compression:
    enabled: true
    mime-types: "application/json,application/javascript,image/svg+xml,text/css,text/html,text/plain,text/xml"
    min-response-size: 2048
  error.whitelabel.enabled: false
  port: 9083
  tomcat.threads:
    min-spare: 10
    max: 50

spring:
  jmx.enabled: false
  mvc.format:
    date: "iso"
    date-time: "iso"
    time: "iso"

---
spring:
  config.activate.on-profile: "development"
  thymeleaf.cache: false

app:
  datasource:
    url: "jdbc:postgresql://localhost/solarnetwork"
    username: "solarnet"
    password: "solarnet"

debug: true

server:
  forward-headers-strategy: "NATIVE"
  tomcat.redirect-context-root: true

---
spring:
  config.activate.on-profile: "production"

server:
  forward-headers-strategy: "NATIVE"
  tomcat.redirect-context-root: true
