<%@ taglib prefix="pack" uri="http://packtag.sf.net" %>
<pack:style>
	/css/bootstrap.css
	/css/bootstrap-theme.css
	/css/global.css
	/css/edit-node.css
</pack:style>
<pack:script> 
	/js-lib/jquery-2.1.1.js
	/js-lib/jquery.form.js
	/js-lib/jquery.maphilight.js
	/js-lib/jquery.timezone-picker.js
	/js-lib/bootstrap.js
	/js/global.js
	/js/login.js
	/js/register.js
	/js/my-nodes.js
	/js/auth-tokens.js
	/js/alerts.js
</pack:script>
