\i ./dist/datum/aggregator.sql
\i ./dist/datum/datumAggregate.sql
\i ./dist/datum/logLocationAggregateMessage.sql
\i ./dist/datum/logNodeAggregateMessage.sql
\i ./dist/datum/runningTotal.sql
\i ./dist/datum/slotAggregator.sql
\i ./dist/datum/totalor.sql
\i ./dist/math/calculateAverageOverHours.sql
\i ./dist/math/calculateAverages.sql
\i ./dist/math/fixPrecision.sql
\i ./dist/util/addTo.sql
\i ./dist/util/intervalMs.sql
\i ./dist/util/mergeObjects.sql
\i ./dist/util/objectPathMatcher.sql
\i ./dist/util/searchFilter.sql
