/**
 * OSCP Capacity Provider configuration.
 */
CREATE TABLE solaruser.user_oscp_cp_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT user_oscp_cp_conf_pk PRIMARY KEY (user_id,id),
	CONSTRAINT user_oscp_cp_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);

/**
 * OSCP Capacity Optimizer configuration.
 */
CREATE TABLE solaruser.user_oscp_co_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT user_oscp_co_conf_pk PRIMARY KEY (user_id,id),
	CONSTRAINT user_oscp_co_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);

/**
 * OSCP Capacity Group configuration.
 */
CREATE TABLE solaruser.user_oscp_cg_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	cname			CHARACTER VARYING(64) NOT NULL,
	ident			CHARACTER VARYING(128) NOT NULL,
	meas_secs		INTEGER NOT NULL CHECK (meas_secs > 0),
	cp_id			BIGINT NOT NULL,
	co_id			BIGINT NOT NULL,
	sprops			JSONB,
	CONSTRAINT user_oscp_cg_conf_pk PRIMARY KEY (user_id,id),
	CONSTRAINT user_oscp_cg_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT user_oscp_cg_conf_cp_fk FOREIGN KEY (user_id,cp_id)
		REFERENCES solaruser.user_oscp_cp_conf (user_id,id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT user_oscp_cg_conf_co_fk FOREIGN KEY (user_id,co_id)
		REFERENCES solaruser.user_oscp_co_conf (user_id,id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);
