/******************************************************************************
 * TABLE solarnet.sn_loc_req
 *
 * Table for location creation requests.
 */
CREATE TABLE solarnet.sn_loc_req (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id		BIGINT NOT NULL,
	status 		CHARACTER(1) NOT NULL,
	jdata		JSONB NOT NULL,
	loc_id		BIGINT,
	message		TEXT,
	CONSTRAINT sn_loc_req_pk PRIMARY KEY (id)
);

CREATE INDEX sn_loc_req_user_idx ON solarnet.sn_loc_req (user_id, status);
