CREATE SCHEMA IF NOT EXISTS solaroscp;

/**
 * OSCP Flexibility Provider configuration.
 */
CREATE TABLE solaroscp.oscp_fp_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	token			CHARACTER VARYING(64) NOT NULL,
	CONSTRAINT oscp_fp_conf_pk PRIMARY KEY (user_id, id),
	CONSTRAINT oscp_fp_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_fp_conf_token_unq UNIQUE (token)
);

/**
 * OSCP Capacity Provider configuration.
 */
CREATE TABLE solaroscp.oscp_cp_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT oscp_cp_conf_pk PRIMARY KEY (user_id, id),
	CONSTRAINT oscp_cp_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_cp_conf_url_unq UNIQUE (user_id, url)
);

/**
 * OSCP Capacity Optimizer configuration.
 */
CREATE TABLE solaroscp.oscp_co_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT oscp_co_conf_pk PRIMARY KEY (user_id, id),
	CONSTRAINT oscp_co_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_co_conf_url_unq UNIQUE (user_id, url)
);

/**
 * OSCP Capacity Group configuration.
 */
CREATE TABLE solaroscp.oscp_cg_conf (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	cname			CHARACTER VARYING(64) NOT NULL,
	ident			CHARACTER VARYING(128) NOT NULL,
	meas_secs		INTEGER NOT NULL CHECK (meas_secs > 0),
	cp_id			BIGINT NOT NULL,
	co_id			BIGINT NOT NULL,
	sprops			JSONB,
	CONSTRAINT oscp_cg_conf_pk PRIMARY KEY (user_id, id),
	CONSTRAINT oscp_cg_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_cg_conf_cp_fk FOREIGN KEY (user_id, cp_id)
		REFERENCES solaroscp.oscp_cp_conf (user_id, id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_cg_conf_co_fk FOREIGN KEY (user_id, co_id)
		REFERENCES solaroscp.oscp_co_conf (user_id,id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_cg_conf_unq UNIQUE (user_id, ident)
);

/**
 * OSCP Asset configuration.
 *
 * The `iprops*` and `eprops*` columns define the datum stream properties to include
 * in the asset measurement. The `*_unit` column defines the unit used in OSCP,
 * and the `*_mult` column defines a mutliplication factor to multiply the datum
 * property values by to convert to the defined unit. For example if the unit is
 * defined as `kW` but the datum property is in `W`, a multiplier of `1000` should
 * be configured.
 *
 * For instantaneous measurements, the datum stream properties are assumed to have
 * an `Instantaneous` datum property classification. Energy measurements are assumed
 * to have `Accumulating` datum property classification.
 */
CREATE TABLE solaroscp.oscp_asset_conf (
	user_id			BIGINT NOT NULL,
	cg_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	cname			CHARACTER VARYING(64) NOT NULL,
	node_id			BIGINT NOT NULL,
	source_id		CHARACTER VARYING(64) NOT NULL,
	category		SMALLINT NOT NULL,		-- asset category
	iprops          TEXT[] NOT NULL,		-- instantaneous measurement datum property names
	iprops_unit		SMALLINT NOT NULL,		-- instantaneous measurement datum property unit enum
	iprops_mult		DECIMAL,				-- instantaneous measurement multiplication factor
	iprops_phase	SMALLINT NOT NULL,		-- instantaneous phase
	eprops          TEXT[] NOT NULL,		-- energy measurement datum property names
	eprops_unit		SMALLINT NOT NULL,		-- energy measurement datum property unit enum
	eprops_mult		DECIMAL,				-- energy measurement multiplication factor
	etype			SMALLINT NOT NULL,		-- energy type
	sprops			JSONB,
	CONSTRAINT oscp_asset_conf_pk PRIMARY KEY (user_id, id),
	CONSTRAINT oscp_asset_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT oscp_asset_conf_cg_fk FOREIGN KEY (user_id, cg_id)
		REFERENCES solaroscp.oscp_cg_conf (user_id, id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);
