CREATE TABLE solarcommon.app_setting (
	created		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	skey		VARCHAR(255) NOT NULL,
	stype		VARCHAR(255) NOT NULL,
	svalue		VARCHAR(4096) NOT NULL,
	CONSTRAINT app_settings_pk PRIMARY KEY (skey, stype)
);
