/**
 * OSCP Capacity Provider configuration.
 */
CREATE TABLE solaruser.user_oscp_cp_conf (
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id			BIGINT NOT NULL,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT user_oscp_cp_conf_pk PRIMARY KEY (id),
	CONSTRAINT user_oscp_cp_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);

/* Add index on user_id so we can show all entities for user. */
CREATE INDEX user_oscp_cp_conf_user_idx ON solaruser.user_oscp_cp_conf (user_id);


/**
 * OSCP Capacity Optimizer configuration.
 */
CREATE TABLE solaruser.user_oscp_co_conf (
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id			BIGINT NOT NULL,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	reg_status		SMALLINT NOT NULL,
	cname			CHARACTER VARYING(64) NOT NULL,
	url				CHARACTER VARYING(256) NOT NULL,
	token			CHARACTER VARYING(64) NOT NULL,
	sprops			JSONB,
	CONSTRAINT user_oscp_co_conf_pk PRIMARY KEY (id),
	CONSTRAINT user_oscp_co_conf_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);

/* Add index on user_id so we can show all entities for user. */
CREATE INDEX user_oscp_co_conf_user_idx ON solaruser.user_oscp_co_conf (user_id);
