CREATE SCHEMA IF NOT EXISTS solardin;

ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA solardin REVOKE ALL ON FUNCTIONS FROM PUBLIC;

/**
 * Account-wide datum input username/password credentials.
 *
 * @column user_id 		the ID of the account owner
 * @column username 	the username
 * @column created		the creation date
 * @column modified		the modification date
 * @column enabled		a flag to mark the certificate as enabled for use by application or not
 * @column expires		the expiration date
 * @column password		the password
 */
CREATE TABLE solardin.din_credential (
	user_id			BIGINT NOT NULL,
	username		CHARACTER VARYING(64) NOT NULL,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	expires			TIMESTAMP WITH TIME ZONE NOT NULL,
	password		CHARACTER VARYING(64) NOT NULL,
	CONSTRAINT din_ca_cert_pk PRIMARY KEY (user_id, username),
	CONSTRAINT din_ca_cert_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);


/**
 * Account-wide datum input transform service configuration.
 *
 * @column user_id 		the ID of the account owner
 * @column id 			the ID of the configuration
 * @column created		the creation date
 * @column modified		the modification date
 * @column cname		friendly name
 * @column sident		the transform service identifier
 * @column sprops		the transform service settings
 */
CREATE TABLE solardin.din_xform (
	user_id			BIGINT NOT NULL,
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	cname			CHARACTER VARYING(64) NOT NULL,
	sident			CHARACTER VARYING(128) NOT NULL,
	sprops			jsonb,
	CONSTRAINT din_xform_pkey PRIMARY KEY (user_id, id),
	CONSTRAINT din_xform_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);


/**
 * Datum input overall endpoint configuration.
 *
 * @column user_id 		the ID of the account owner
 * @column id 			UUID for the configuration
 * @column created		the creation date
 * @column modified		the modification date
 * @column enabled		a flag to mark the configuration as enabled for use by application or not
 * @column cname		friendly name
 * @column node_id		the default node ID to use, if the transform does not provide one
 * @column source_id	the default source ID to use, if the transform does not provide one
 * @column xform_id		the din_xform ID to use
 */
CREATE TABLE solardin.din_endpoint (
	user_id			BIGINT NOT NULL,
	id				UUID NOT NULL,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	cname			CHARACTER VARYING(64) NOT NULL,
	node_id			BIGINT,
	source_id		CHARACTER VARYING(64),
	xform_id		BIGINT,
	CONSTRAINT din_endpoint_pk PRIMARY KEY (user_id, id),
	CONSTRAINT din_endpoint_user_fk FOREIGN KEY (user_id)
		REFERENCES solaruser.user_user (id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT din_endpoint_xform_fk FOREIGN KEY (user_id, xform_id)
		REFERENCES solardin.din_xform (user_id, id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE SET NULL
);


/**
 * Datum input endpoint authorization credentials configuration.
 *
 * @column user_id 		the ID of the account owner
 * @column endpoint_id 	the ID of the solardin.din_endpoint record
 * @column username		the authorized username
 * @column created		the creation date
 * @column modified		the modification date
 * @column enabled		a flag to mark the configuration as enabled for use by application or not
 */
CREATE TABLE solardin.din_endpoint_auth_cred (
	user_id			BIGINT NOT NULL,
	endpoint_id		UUID NOT NULL,
	username		CHARACTER VARYING(64) NOT NULL,
	created			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled			BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT din_endpoint_auth_cred_pk PRIMARY KEY (user_id, endpoint_id, username),
	CONSTRAINT din_endpoint_auth_cred_endpoint_fk FOREIGN KEY (user_id, endpoint_id)
		REFERENCES solardin.din_endpoint (user_id, id) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE,
	CONSTRAINT din_endpoint_auth_cred_cred_fk FOREIGN KEY (user_id, username)
		REFERENCES solardin.din_credential (user_id, username) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE CASCADE
);
